### ISSUE TITLE
關於 Ajax 的進入時機點

### ISSUE THREAD

**Issue by angelyaaaaa** [shiningjason1989/react-quick-tutorial#10]
為何範例中的 ajax 會放在 componentDidMount() 這個時間點呢 ?
按照這個流程下來，應該在 render() 之前就去將 todos.json 放進來會比較好吧 ? 所以是放在 componentWillMount() 
還是說，大部分由於通用性的關係，會比較常放在 componentDidMount() 這個時間點呢 ?

**Comment by shiningjason** [comment]
Hi @angelyaaaaa,

因為去向後端請求資料是需要一段時間的，
如果我們不希望整個頁面 blocking 在請求的地方，
而想要讓使用者可以先瀏覽及操作頁面的話；
請求的方式我們會使用 AJAX 非同步的方式，所以既然是非同步，
放在 componentWillMount, componentDidMount 其實就沒有差別了。

###### AJAX 放在 componentWillMount 的順序：
1. componentWillMount → ajax request
2. render (沒有 todos 資料的初始頁面，你可以顯示 loading 中)
3. componentDidMount
4. ajax response → setState
5. render (得到 todos 資料，重新渲染頁面給使用者)

###### AJAX 放在 componentDidMount 的順序：
1. componentWillMount
2. render (沒有 todos 資料的初始頁面，你可以顯示 loading 中)
3. componentDidMount → ajax request
4. ajax response → setState
5. render (得到 todos 資料，重新渲染頁面給使用者)

那麼就像你說的，為了 universal，
componentWillMount 會被 server 和 client 調用，
而 componentDidMount 只會被 client 調用；
如果是 AJAX 那還是如同 [官方文件](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount) 建議我們的放在 componentDidMount。

如果是 Single Page Application，不考慮在 Server render 的話，就沒有差別了。

希望有幫助到你囉～！
😎
