### ISSUE TITLE
level 15的register

### ISSUE THREAD

**Issue by jimmy0435** [shiningjason1989/react-quick-tutorial#11]
版主你好,

想請問個問題

1.
這段程式碼是會在哪個時候觸發呢，不太了解這是在哪邊啟動註冊的呢，是在TodoApp將TodoStore從window.App拿出來的時候嗎?

``` js
dispatchToken: AppDispatcher.register((action) => {
  switch (action.type) {
    case ActionTypes.LOAD_TODOS_SUCCESS:
      _todos = action.todos;
      _emitter.emit(CHANGE_EVENT); // 5. 當資料改變，必須觸發事件
      break;
    case ActionTypes.CREATE_TODO:
      _todos = _createTodo(_todos, action.title);
      _emitter.emit(CHANGE_EVENT);
      break;
    case ActionTypes.UPDATE_TODO: /* 略 */
    case ActionTypes.TOGGLE_TODO: /* 略 */
    case ActionTypes.DELETE_TODO: /* 略 */
  }
})
```

**Comment by shiningjason** [comment]
Hi @qwe852,

不好意思那麼晚看到你的留言！

TodoStore 向 AppDispatcher 註冊 callback 是在 App 一啟動時就做的事情，順序大概是：
1. html load TodoStore.js
2. browser 執行 TodoStore.js，建立 window.app.TodoStore 的變數；這時候就調用 `AppDispatcher.register` 囉，並且把 Dispatcher 回傳的 token 指派給 window.app.TodoStore。
3. TodoApp 跟 TodoStore 取得資料。

希望有回答到你的問題囉！

**Comment by jimmy0435** [comment]
有回答到我的問題，謝謝你的回覆!
