### ISSUE TITLE
rest

### ISSUE THREAD

**Issue by Rylai-Zihang** [shiningjason1989/react-quick-tutorial#12]
解構賦值rest參數要使用出錯

**Comment by Rylai-Zihang** [comment]
你好：
在level06中：
我嘗試使用解構賦值卻遇到了問題，程序如下：
`const state = {
            value1: 'value1',
            value2: 'value2',
            value3: '3'
        };
        const { value1, value2,...rest} = state;
    console.log(value1 +" and "+ value2 + "and" + rest);
`

報錯信息為 Unexpected token
![image](https://cloud.githubusercontent.com/assets/14244068/19375133/b528d916-9203-11e6-88eb-77f9c90688ed.png)

請問這是怎麼回事呢？

**Comment by shiningjason** [comment]
Hi @Rylai-Zihang,

因為物件的解構賦值是 ES6 的語法，你必須使用 Babel 轉譯成 ES5，才能讓瀏覽器跑得動（目前尚無瀏覽器支援該語法）。

在範例中，我有使用 babel/browser.js 幫我做這件事；如果你想在線上試試這語法，可以使用 [jsfiddle](https://jsfiddle.net/), [jsbin](https://jsbin.com/)，這兩個服務都能將 JavaScript 模式換成 Babel 模式。

而在真實專案中，大多人是寫 ES6/ES7，然後都是使用 webpack/babel 將 code 都轉成 ES5，並且 bundle 在發佈，瀏覽器就可以正確地跑 App。

另外，如果你想看看，到底 ES6 的語法編譯成 ES5 會是長什麼樣子，可以把 ES6 語法貼在 [Babel 線上轉譯器](http://babeljs.io/repl/) 的左邊，看看右邊發生了什麼事。

希望有幫助到你囉！

**Comment by Rylai-Zihang** [comment]
Thanks a lot! Your tutorial has helped me a lot!
I'll keep learning React~

在 2016-10-15 10:42:33，"Jason Chung" notifications@github.com 写道：

Hi @Rylai-Zihang,

因為物件的解構賦值是 ES6 的語法，你必須使用 Babel 轉譯成 ES5，才能讓瀏覽器跑得動（目前尚無瀏覽器支援該語法）。

在範例中，我有使用 babel/browser.js 幫我做這件事；如果你想在線上試試這語法，可以使用 jsfiddle, jsbin，這兩個服務都能將 JavaScript 換成 Babel。

而在真實專案中，大多人是寫 ES6/ES7，然後都是使用 webpack/babel 將 code 都轉成 ES5，並且 bundle 在發佈，瀏覽器就可以正確地跑 App。

另外，如果你想看看，到底 ES6 的語法編譯成 ES5 會是長什麼樣子，可以把 ES6 語法貼在 Babel 線上轉譯器 的左邊，看看右邊發生了什麼事。

希望有幫助到你囉！
