### ISSUE TITLE
外部js import的方法

### ISSUE THREAD

**Issue by YoshiLiao** [shiningjason1989/react-quick-tutorial#14]
外部js檔案匯入
通常比較常看到的是
import與export default class名+ import xxx from './class'
window.App = {} 這種方式的import方法比較少見
這是ES6獨有的語法嗎？
不知道哪裡可以找到相關的資料學習window這類匯入方式～謝謝

**Comment by shiningjason** [comment]
Hi @YoshiLiao,

目前的專案上我都是用 ES6 的 import/export，而這通常必須要用到 webpack/babel 等建置工具，才能讓 browser 吃我們的 app。

而這份教材使用 window.App 的方式，只是因為當初考量到要讓大家可以跳過 webpack/babel 的坑，直接進入 React 的世界，所以才使用這種最原始的模組化方式。

所以它並不是什麼新方法；只是想表達 React 是元件化的思維，可以把一個個元件模組化，拆成一支支的檔案，所用的最簡易和最原始的方法。

本來只是想帶給大家模組化的開發體驗，所以就沒有細講 AMD, CommonJS module, ES6 module 等其他類似的解決方案了。

最後還是要講一下，千萬別用 window.App 這種方式在正式的專案上，很怕不小心誤導了大家 XD

**Comment by YoshiLiao** [comment]
Jason~感謝你的回覆～
想問課程內容與這份教材有哪些不同呢？
另外想問，你開設的課程，會談到react native嗎？謝謝～

**Comment by shiningjason** [comment]
Hi @YoshiLiao,

你說的課程是放在 teachable 上面的嗎？

如果是的話，最大的不同是線上課程上面是有錄製影音的；
然後裡面並沒有談到 React Native 唷！
