### ISSUE TITLE
請問 AppDispatcher 出了甚麼錯?

### ISSUE THREAD

**Issue by taiyan33** [shiningjason1989/react-quick-tutorial#17]
Level 16. 完成 Controller View：讓元件同步資料狀態
https://github.com/shiningjason1989/react-quick-tutorial/tree/master/level-16_flux-controller-view

錯誤訊息
Uncaught ReferenceError: AppDispatcher is not defined(…)

**Comment by shiningjason** [comment]
Hi @taiyan33,

因為 AppDispatcher 定義在 window.App.AppDispatcher 下面，所以你必須從 window.App import 進來：

``` js
const { AppDispatcher } = window.App;
```

而這麼做的用意是因為你如果不想把整支 App 寫在一起，要使用模組的方式分檔案，而且不想直接定義在 global 下怕會用髒 window 的變數；這時，除了像是 commonjs, es6 modules, requirejs 等方法，最簡單的就是指定 window 下一個 App 的模組，所有 App 的模組都指在這下面，而當你需要用時，就必須從 window.App 才能取到。

當然你也可以先直接定義在 global，不要定義在 window.App：

``` js
const AppDispatcher = new Flux.Dispatcher();
```

這時你就可以直接使用 AppDispatcher。

希望有解答到你的問題囉。

**Comment by taiyan33** [comment]
感謝~大大無私地分享~!
每次重構程式都有
↓↓↓↓↓↓↓↓↓↓
Re：ゼロから始める異世界生活

的感覺~又痛苦又爆肝~
但是成功後又會以一點爽~哈哈

音樂也不錯聽:
https://youtu.be/y3RkRhaJPIc?list=RDy3RkRhaJPIc
