### ISSUE TITLE
有關於Level 5. 組合多個 React 元件

### ISSUE THREAD

**Issue by yulai** [shiningjason1989/react-quick-tutorial#18]
嗨，感謝您提供如此簡顯易懂的教學
但這裡有小小問題
我按照demo上code撰寫後，發現他出現空白
包含我把所有code貼在自己專案都是空白
請問一下這有可能是什麼問題呢？謝謝
(初學者:'( 還不是很能知道問題出在哪裡><)
附上錯誤截圖
![2017-01-24 6 04 16](https://cloud.githubusercontent.com/assets/6111332/22242793/ae37ce6c-e25f-11e6-8d58-2917592f8294.png)

**Comment by shiningjason** [comment]
hi @yulai,

我剛剛試著重現妳的問題，看起來妳是直接在瀏覽器打開 `index.html`，所以會遇到這樣的錯誤。

如果是的話，你可能需要一台 server 去服務這些靜態檔案，譬如：[live-server](https://github.com/tapio/live-server)；用法很簡單 -

```sh
npm install -g liver-server
cd ./project
live-server ./

# 最後在瀏覽器打開 http://localhost:8080
```

希望有幫助到妳囉，如果又任何問題可以再留言給我～

---

PS.
或是妳也可以試試看使用 [create-react-app](https://github.com/facebookincubator/create-react-app) 來做練習；如果妳使用官方出的這個工具，在這個範例中的 sample code 可能需要做一些修正，因為這個範例中並沒有使用 commonjs module，而在實際專案中應該是要使用的，所以 create react app 會比較貼近現實開發體驗。

**Comment by CurryLiSun** [comment]
請問作者
我是使用VS Code作為練習環境
VS Code中有live server的套件
但是我使用這個套件練習到Level5也遇到相同問題

如圖
![image](https://user-images.githubusercontent.com/22556437/51300306-67161e80-1a66-11e9-887c-f8a0f7da0746.png)

**Comment by CurryLiSun** [comment]
作者好
後來我解決了這個問題
原因是在index.html當中的引入順序

![image](https://user-images.githubusercontent.com/22556437/51300944-7eeea200-1a68-11e9-91c8-1612b9fe0f93.png)

在上圖中我引入的順序是

`

    <script type="text/babel" src="./TodoApp.js"></script>

    <script type="text/babel" src="./InputField.js"></script>

    <script type="text/babel" src="./TodoHeader.js"></script>

    <script type="text/babel" src="./TodoList.js"></script>
`

所以TodoApp.js這支程式會先被執行，但在這支程式中並沒有InputField、TodoHeader、TodoList
這幾個的組件，所以報錯誤Warning: React.createElement
而我把程式碼順序換成以下

`

    <script type="text/babel" src="./InputField.js"></script>

    <script type="text/babel" src="./TodoHeader.js"></script>

    <script type="text/babel" src="./TodoList.js"></script>

    <script type="text/babel" src="./TodoApp.js"></script>
`

就正常顯示了
![image](https://user-images.githubusercontent.com/22556437/51301080-ead10a80-1a68-11e9-952a-69d6ab9af9f2.png)
