### ISSUE TITLE
Level 6: InputField 的 placeholder 傳值方法是簡寫嗎？

### ISSUE THREAD

**Issue by kalun1988** [shiningjason1989/react-quick-tutorial#3]
TodoApp.js

```
        <InputField placeholder="新增待辦清單" />
```

InputField.js (git上的)

```

  render() {
    return (
      <input {...this.props} type="text" />
    );
  }
```

InputField.js (參巧TodoItem的)

```
  render() {
    const {
      placeholder
    } = this.props;
    return <input type="text" placeholder={placeholder} />;
  }
```

InputField 的 placeholder 傳值方法是簡寫嗎？可以省略html attribute?

---

借機會先感謝Jason大大建立這份tutorial，讓新手可一關關走下去。
累計看了幾個小時，比較好的閱讀方法是git clone下來，對比每個關之間的變化，再看看筆記的補充

**Comment by shiningjason** [comment]
哈囉，@kalun1988：

是的，repo 上的 InputField 我用了 React 提供的 **_[JSX Spread Attributes](https://facebook.github.io/react/docs/jsx-spread.html)**_ 的功能；
我也將用法筆記在 _[Level-06_學習筆記 1. [React] 傳遞 props 的方式](https://github.com/shiningjason1989/react-quick-tutorial/tree/master/level-06_transferring-props#1-react-傳遞-props-的方式)_ 中。

這一個用法很常用在上層元件傳遞的 props，也要原封不動傳遞給下層元件的話：

``` js
// InputField 要將 TodoApp 傳遞的 props 傳給下層元件 input：
const TodoApp = () => (
  <div>
    <InputField placeholder="hello" value="hello" onChange={() => {}} style={{}} />
  </div>
);

// 1. 比較麻煩的寫法：
const InputField = (props) => (
  <input
    placeholder={props.hello}
    value={props.value}
    onChange={props.onChange}
    style={props.style}
    type="text"
  />
);

// 2. 比較方便的寫法：
//    這語法的白話大概是「將 props 物件的屬性打散成 key, value 後，丟進去給 input」
//    因此省去了 html attributes
const InputField = (props) => (
  <input {...props} type="text" />
);

// 3. 需要注意的是：
//    如果你不想讓 props 一股腦兒的丟到子元件中，
//    你必須將不想放進去的參數排除。
//
//    如下方這一個範例，上層元件傳遞的 style 不是要給 input 的，是給 div 的。
//
//    可以使用 [ES6] Object rest properties 語法達到這件事情，
//    下方等同在 class 中，使用 const { style, ...rest } = this.props;
const InputField = ({ style, ...rest }) => (
  <div style={style}>
    <input {...rest} type="text" />
  </div>
);
```

如果你想更深入的了解 **_JSX spread attributes**_：

``` js
// 1. JSX spread attributes：
const InputField = (props) => (
  <input {...props} type="text" />
);

// 2. JSX 轉成 ES6 的話：
const InputField = (props) => (
  React.createElement('input', { ...props, type: 'text' });
);

// 3. ES6 轉成 ES5 的話：
var InputField = function(props) {
  return React.createElement('input', Object.assign({}, props, { type: 'text' }));
};
```

所以，JSX spread attributes 其實是使用了 **_[ES6] Object spread properties**_：

``` js
// 1. 如果在 ES6 中，inputProps 要 merge props 中的屬性：
const props = { a: 1, b: 2 };
const inputProps = { ...props, c: 3 }; // { a:1, b: 2, c: 3 };

// 2. ES6 轉成 ES5 的話：
var props = { a: 1, b: 2 };
var inputProps = Object.assign({}, props, { type: 'text' });
```

所以，比較重要的語法是 **_[Level-06_學習筆記 4. [ES6] Object spread properties](https://github.com/shiningjason1989/react-quick-tutorial/tree/master/level-06_transferring-props#4-es6-object-spread-properties)**_，它讓上面都成為可能！

參考連結
1. [Object.assign() | MDN](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
2. [Object spread properties spec](https://github.com/sebmarkbage/ecmascript-rest-spread)
3. [JSX spread attributes](https://facebook.github.io/react/docs/jsx-spread.html)

---

希望有幫助到你囉！
也謝謝你的 feedback：）
