### ISSUE TITLE
大大，您富姦了嗎

### ISSUE THREAD

**Issue by ayuha406645** [shiningjason1989/react-quick-tutorial#4]
拍謝因為快六月底了
我看第三章的內容未更新(title也未調整)
所以來提醒大大一下 :)
大大加油!!

**Comment by shiningjason** [comment]
@ayuha406645：

哈囉，很抱歉我休刊了一個月... :scream::scream::scream:
接下來的第三章我會在七月中以前完成。

請再給我
![continue](https://cloud.githubusercontent.com/assets/652135/16591230/6d9472b2-430d-11e6-99ec-545fe214ecfd.png)
的機會啊！:muscle::muscle::muscle:

還是要講一下為什麼我休刊了那麼久，因為在忙錄其他的事情；
還有想說要自己寫一篇 [深入淺出 Redux](https://medium.com/4cats-io/深入淺出-redux-7b08403c4957) 的文章卻遲遲沒靈感，所以難產了一個月～

在誠摯的道歉一次！:bow:

**Comment by shiningjason** [comment]
結束連載囉～ :kissing_smiling_eyes:

**Comment by ayuha406645** [comment]
辛苦大大了!!! 
感謝大大的深入淺出指導阿!!!
感謝大大!!!
