### ISSUE TITLE
Unknown prop `onSubmitEditing` on <input> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by zhjiangexe** [shiningjason1989/react-quick-tutorial#5]
24 小時，React 快速入門，Level 10
InputField.js
我判斷是因為寫了{...this.props}，取到上層傳給input沒有的屬性，而造成問題
請問除了自己重新取用props自己塞，還有沒有簡便的方法

``` jsx
<input 
    {...this.props}
    type="text"
    value={this.state.value}
    onChange={this.handleChange}
    onKeyDown={this.handleKeyDown}
/>
```

以下為瀏覽器發生的錯誤

```
react.js:20209 Warning: Unknown prop `onSubmitEditing` on <input> tag. 
Remove this prop from the element. 
For details, see https://fb.me/react-unknown-prop
    in input (created by InputField)
    in InputField (created by TodoApp)
    in div (created by TodoApp)
    in TodoApp
```

**Comment by shiningjason** [comment]
Hi @rocktsuki,

你遇到的問題，我剛剛去查了一下，官方在一個月前的 [v15.2.0](https://github.com/facebook/react/releases/tag/v15.2.0) 加入這個檢查條件 - _Add warning for unknown properties on DOM elements._，還熱騰騰的；所以這是我第一次看過這個警告！

根據警告中的 [links](https://facebook.github.io/react/warnings/unknown-prop.html)，看起來必須得自己手動提取 props，不能再一股腦地往下送到 standard DOM 了！

所以，在 InputField 中：

``` js
render() {
  const { onSubmitEditing, ...inputProps } = this.props;
  return (<input {...inputProps} />)
}
```

雖然麻煩點，但是的確 **_讓 props 的傳遞更明確**_，
所以我目前尚無想到其他更簡便的方法！

謝謝你提出這個問題，
看來我需要找時間升級一下教材中的 react 版本！

🤔

**Comment by shiningjason** [comment]
@rocktsuki 關於這個 issue，請參考[這串](https://gist.github.com/statianzo/91234d26094ad89c1ff742f41b25d737)討論，雖然仍然是沒有簡易的方式。

**Comment by xiaofan10** [comment]
有没有该方面的库来过滤掉不支持的属性呢？或者我如何建立一个input属性的白名单？都要考虑哪些？
