### ISSUE TITLE
Level 4. const { TodoApp } = window.App;語法

### ISSUE THREAD

**Issue by jimmy0435** [shiningjason1989/react-quick-tutorial#6]
您好
最近開始學習React
對於文章中的語法有一點疑惑

// 3. 從 window.App 中，取得 TodoApp 元件
const { TodoApp } = window.App;

1.這一句語法有點疑問，const的大括號的意思是什麼呢?

2.還有就是既然是要取得window.App.TodoApp為什麼不是const { TodoApp } = window.App.TodoApp;呢?

查了一些資料，可能下的關鍵字不是很好，沒有找到解答QQ
所以來留言提問，謝謝囉

**Comment by shiningjason** [comment]
Hi @qwe852,

可以參考 [lv4 學習筆記3 - 解構賦值](https://github.com/shiningjason1989/react-quick-tutorial/tree/master/level-04_first-component#3-es6-解構賦值-destructuring-assignment)。

或是下方列出 ES5 和 ES6 的差異，兩種取得 TodoApp 的方式是一樣的：

``` js
// ES5 的寫法
var TodoApp = window.App.TodoApp;

// ES6 解構賦值的寫法
var { TodoApp } = window.App;
```

你可以把前面這個大括弧 `{} = App` 當成是 App 這個物件，而 TodoApp 原本是 App 中的屬性，所以 `{ TodoApp } = App` 翻成白話文就是「你要從 App 中提取 TodoApp 這個屬性」。

因此 `const { TodoApp } = window.App.TodoApp` 變成就是要取 `TodoApp.TodoApp` 不是 `App.TodoApp`。

相關連結：[解構賦值 | MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

---

希望有幫助到你囉！

PS. 任何芝麻蒜皮的小事，都歡迎你詢問和討論 😀

**Comment by jimmy0435** [comment]
謝謝你!
原來是我眼殘..
下次會把整篇看清楚再問
不好意思~~~
