### ISSUE TITLE
level3 主線任務實作沒有畫面

### ISSUE THREAD

**Issue by Luxame** [shiningjason1989/react-quick-tutorial#7]
一開始實作有helloworld，只是後面拿掉 `id` 看會發生什麼事情，就變成空白一直沒有畫面，回到一開始也是
https://github.com/Luxame/react/commit/f67e813312d9555d3a2e06ba96f4164fca1a401d
![default](https://cloud.githubusercontent.com/assets/7363178/17506814/729a9b82-5e3e-11e6-89a7-8d9246eae416.png)

**Comment by shiningjason** [comment]
Hi @Luxame,

我剛剛看了你的 code，
你必須引入以下三支程式 react.js, react-dom.js, browser.js，
才會顯示出 hello, world 唷！

完整的 code 請看 [level-03_hello-react/index.html](https://github.com/shiningjason1989/react-quick-tutorial/blob/master/level-03_hello-react/index.html)。

還需要任何協助歡迎你在留言給我：）

**Comment by Luxame** [comment]
@shiningjason1989 有了！是我少引入那三個程式搞出烏龍了Orz
感謝你的幫忙！
謝謝你<(_ _)>
