### ISSUE TITLE
Level 9 &&符號 

### ISSUE THREAD

**Issue by bigtounge5566** [shiningjason1989/react-quick-tutorial#9]
大大你好
  大大你好

Level 9
3. 完成刪除待辦項目功能
<button onClick={() => onDelete && onDelete()}>x</button>
裡面&&的意思 我想了很久都不是很清楚
大大可以提點一下嗎?

**Comment by shiningjason** [comment]
Hi @bigtounge5566,

搜哩現在才看到，
這跟 `if (onDelete) onDelete()` 的意思一樣唷！

就只是判斷上層元件是否有傳遞參數進來，
希望有解答到你囉！
